version: '3.8'

services:
  backend:
    build:
      context: ./backend_python
      dockerfile: Dockerfile
    container_name: velocity-banking-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - DEBUG=False
    volumes:
      - db-data:/app/data
    networks:
      - velocity-banking-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: velocity-banking-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - velocity-banking-network
    restart: unless-stopped

networks:
  velocity-banking-network:
    driver: bridge

volumes:
  db-data:
